name: Build package and test
on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt-get install ruby-dev build-essential debhelper devscripts rpm xalan wget -y
      - name: Install FPM
        run: gem install fpm
      - name: Build Package
        run: ./create_packages
      - name: Test Package
        run: ./ci_test
